In [5]:
import numpy as np
A=np.array([[3,-9],[2,4]])
print(A)

[[ 3 -9]
 [ 2  4]]


In [6]:
B=np.array([-42,2])
Z=np.linalg.solve(A,B)
print(Z)

[-5.  3.]


In [7]:
M=np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
print(M)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [ ]:
c=np.array([6,1,1])
y=np.linalg.solve(M,c)